import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { resolveUserId } from '@/lib/auth-request';
import {
  getSectorRecommendations,
  mapMlToRecommendation,
} from '@/lib/ml-service';
import { sectorIdToDiscipline, disciplineToLabel } from '@/lib/sectors';

// GET /api/recommendations?sector=music
// GET /api/recommendations?sponsorId=<audienceMemberId>  (saved/stored recs for that sponsor)
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const sponsorId = searchParams.get('sponsorId');
    const sector =
      searchParams.get('sector') || searchParams.get('category') || 'music';
    const page = parseInt(searchParams.get('page') || '1', 10);
    const limit = parseInt(searchParams.get('limit') || '10', 10);
    const userId = resolveUserId(request, sponsorId);

    // Stored recommendations for a specific sponsor/audience member (DB-backed,
    // e.g. ones generated by an offline batch job or previously persisted).
    if (sponsorId) {
      const stored = await prisma.recommendation.findMany({
        where: { audienceMemberId: sponsorId },
        include: {
          contentItem: { include: { creator: { include: { user: true } } } },
        },
        orderBy: { score: 'desc' },
        skip: (page - 1) * limit,
        take: limit,
      });

      const total = await prisma.recommendation.count({
        where: { audienceMemberId: sponsorId },
      });

      const data = stored.map((rec) => ({
        id: rec.id,
        talentId: rec.contentItem.creatorId,
        talentName: rec.contentItem.creator.user.username,
        mediaId: rec.contentItemId,
        matchScore: Math.round(rec.score),
        algorithm: rec.algorithm,
        rankPosition: rec.rankPosition,
        createdAt: rec.generatedAt,
      }));

      return NextResponse.json({
        data,
        pagination: { page, limit, total, hasMore: page * limit < total },
        source: 'database',
      });
    }

    // Live sector recommendations via the ML service (sector-top-five).
    const discipline = sectorIdToDiscipline(sector);
    const mlResponse = await getSectorRecommendations(userId, sector);
    const mapped = mlResponse.results.map((item) =>
      mapMlToRecommendation(item, mlResponse.sector)
    );

    const start = (page - 1) * limit;
    const paginated = mapped.slice(start, start + limit);

    return NextResponse.json({
      data: paginated,
      pagination: {
        page,
        limit,
        total: mapped.length,
        hasMore: start + limit < mapped.length,
      },
      source: mlResponse.source,
      sector: mlResponse.sector,
      sectorLabel: discipline ? disciplineToLabel(discipline) : sector,
    });
  } catch (error) {
    console.error('Recommendations fetch error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch recommendations. Is the ML service running?' },
      { status: 502 }
    );
  }
}

// PATCH /api/recommendations - update a stored recommendation's rank/score
// (kept for the sponsor dashboard's "mark as viewed/interested" actions once
// recommendations are persisted into the `Recommendation` table).
export async function PATCH(request: NextRequest) {
  try {
    const body = await request.json();
    const { recommendationId, score, rankPosition } = body;

    if (!recommendationId) {
      return NextResponse.json(
        { error: 'recommendationId is required' },
        { status: 400 }
      );
    }

    const updated = await prisma.recommendation.update({
      where: { id: recommendationId },
      data: {
        ...(score !== undefined && { score }),
        ...(rankPosition !== undefined && { rankPosition }),
      },
    });

    return NextResponse.json(updated);
  } catch (error) {
    console.error('Recommendation update error:', error);
    return NextResponse.json(
      { error: 'Failed to update recommendation' },
      { status: 500 }
    );
  }
}
